# SPDX-License-Identifier: Apache-2.0

DEVICE_PATH := device/zte/franklin
PRODUCT_IS_ATV := true
PRODUCT_CHARACTERISTICS := tv,nosdcard
PRODUCT_USE_DYNAMIC_PARTITIONS := true
PRODUCT_BUILD_SUPER_PARTITION := true

# Amlogic G12A platform support (audio, media, graphics, init and dynamic
# partition plumbing). The common product also includes its vendor package.
$(call inherit-product, device/amlogic/g12-common/g12.mk)

# Device-specific proprietary files are generated by extract-files.sh.
$(call inherit-product-if-exists, vendor/zte/franklin/franklin-vendor.mk)

# Stock first API level is 28; the stock vendor image is Android 12 / API 31.
PRODUCT_SHIPPING_API_LEVEL := 28
PRODUCT_PRODUCT_PROPERTIES += \
    ro.product.first_api_level=28 \
    ro.zygote=zygote32

# Stock property helper selects the installed Wi-Fi and Bluetooth chipset.
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/init.franklin.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.franklin.rc \
    $(DEVICE_PATH)/init.amlogic.wifi_buildin.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.amlogic.wifi_buildin.rc

# The common device tree can build modules from source. Franklin instead uses
# the modules shipped with its stock 4.9.269 kernel, extracted as vendor blobs.
# Use the stock Droidlogic Wi-Fi HIDL service, not the common generic IWifi HAL.
PRODUCT_PACKAGES := $(filter-out mali media optee-module android.hardware.wifi@1.0-service,$(PRODUCT_PACKAGES))

# Never copy per-device provisioning material from the dump into a ROM build.
# These exclusions are a second guard; extract-files.sh also removes them from
# the common proprietary-file lists before extraction.
FRANKLIN_SENSITIVE_COPY_PATTERNS := \
    vendor/amlogic/g12-common/proprietary/odm/etc/firmware/firmware.le:% \
    vendor/amlogic/g12-common/proprietary/vendor/etc/drm/playready/bgroupcert.dat:% \
    vendor/amlogic/g12-common/proprietary/vendor/etc/drm/playready/zgpriv.dat:% \
    vendor/amlogic/g12-common/proprietary/vendor/etc/drm/playready/zgpriv_protected.dat:% \
    vendor/amlogic/g12-common/proprietary/vendor/bin/tee_hdcp:% \
    vendor/amlogic/g12-common/proprietary/vendor/bin/tee_key_inject:% \
    vendor/amlogic/g12-common/proprietary/vendor/bin/hdcp_tx22:% \
    vendor/amlogic/g12-common/proprietary/vendor/etc/init/tee_hdcp.rc:% \
    vendor/amlogic/g12-common/proprietary/vendor/etc/init/tee_key_inject.rc:% \
    vendor/amlogic/g12-common/proprietary/vendor/bin/hw/android.hardware.drm@1.4-service.playready:% \
    vendor/amlogic/g12-common/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.playready.rc:% \
    vendor/amlogic/g12-common/proprietary/vendor/lib/libplayready.so:% \
    vendor/amlogic/g12-common/proprietary/vendor/lib/libplayreadymediadrmplugin.so:% \
    vendor/zte/franklin/proprietary/odm/etc/firmware/firmware.le:%
PRODUCT_COPY_FILES := $(filter-out $(FRANKLIN_SENSITIVE_COPY_PATTERNS),$(PRODUCT_COPY_FILES))
PRODUCT_PACKAGES := $(filter-out manifest_android.hardware.drm@1.4-service.playready,$(PRODUCT_PACKAGES))
